### ISSUE TITLE
Add shell in Jammy tiny stack

### ISSUE THREAD

**Issue by zhoufenqin** [paketo-buildpacks/jammy-tiny-stack#114]
we hope to use jammy-tiny-stack when build a java-native-image because it can make the container image size smaller.

But I think `shell` is an important lib for us because we can use `kubectl exec -it xx -- bash` for some troubleshooting in our k8s. But I find that currently jammy-tiny-stack image doesn't include `shell`, is there any way to include this?

**Comment by zhoufenqin** [comment]
any update?

**Comment by robdimsdale** [comment]
Hi @zhoufenqin,

I understand the value in having a shell for debugging - I've encountered this myself. But one of the goals of the tiny stack is a minimal image for the smallest possible size and security footprint. That's why there is no shell, and we are not likely to add one to this stack.

I understand it makes debugging harder, but there are built-ins (like `ls`, etc) which can help. You can also always rebuild the app on the [base stack](https://github.com/paketo-buildpacks/jammy-base-stack) which does have a shell.

Given that, I will close this issue as won't-implement.

**Comment by ragaskar** [comment]
Hi @robdimsdale 

Sorry to necro, but this issue provides good background context for my question. 

Is there a particular approach one needs to take in order to use the built-ins? 

I am issuing e.g.: 

` kubectl exec --stdin --tty my-jammy-tiny-stack-image -- ls`

(and various permutations w/o the --stdin --tty flags) 

and am getting back 

```
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "bbafba99a4569ece22310bfc2cadb216de4635132684aa0f7b9b67e1811bdf45": OCI runtime exec failed: exec failed: unable to start container process: exec: "ls": executable file not found in $PATH: unknown
``` 

I presume I'm doing something silly here, but an example would help. I scanned the paketo docs and didn't see anything relevant.
